[workspace]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "python-sandbox"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dev = "marimo edit"

[dependencies]
python = ">=3.14.4,<3.15"

[pypi-dependencies]
marimo = ">=0.23.4, <0.24"
pyxel = ">=2.9.5, <3"
numpy = ">=2.4.4, <3"
